### PR TITLE
Added LinuxARM64 Corretto support to existing changesets

### PR DESCRIPTION
**Pull request by pnavais**
Added versions for JDK 8.262.10.1 and 11.0.8.10.1.

### CODE REVIEW

**Comment by pnavais** [comment]
Hi @dvdkruk , i've just added to your db migrations changes support for Amazon's Corretto JDK for LinuxARM64 in existing changeset versions. This can be merged after your PR (https://github.com/sdkman/sdkman-cli/pull/769) gets finally merged.

**Comment by dvdkruk** [comment]
Hi @pnavais, for adding a new platform candidate, you need to always create a new change set migration and up the migration set version number. Similarly to how it is done in commit https://github.com/dvdkruk/sdkman-db-migrations/commit/5c8b8dad1cfe80b84afbad110626e9a41740bd28 This is because the existing migration is already applied to the database and persisted, so a new one needs to be created to add this new platform candidate for Correto.

**Comment by pnavais** [comment]
Understood. Moved both to a new changeset as per [5c8b8da](https://github.com/dvdkruk/sdkman-db-migrations/commit/5c8b8dad1cfe80b84afbad110626e9a41740bd28)

**Review by dvdkruk — APPROVED** [review]
LGTM

**Pull request merged**
